# Generated by Django 2.2.12 on 2021-09-26 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('midlename', models.CharField(max_length=100, verbose_name='Отчество')),
                ('citizenship', models.CharField(max_length=100, verbose_name='Гражданство')),
                ('nationality', models.CharField(max_length=100, verbose_name='Национальнось')),
                ('wish_post', models.CharField(max_length=120, verbose_name='Желаемая должность')),
                ('about_yourself', models.TextField(blank=True, null=True)),
                ('accounts', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=200, verbose_name='E-mail')),
                ('contacts', models.CharField(max_length=10, verbose_name='Номер')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='resume', verbose_name='Картинки')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_image', to='resume.Resume')),
            ],
        ),
    ]
